open_id_jwks_uri = "https://dev-lr8vwbeyc7gmi0w2.us.auth0.com/.well-known/jwks.json"
open_id_audience = "read-every-word-bff-prod"
open_id_domain    = "dev-lr8vwbeyc7gmi0w2.us.auth0.com"
open_id_client_id = "YIirO5dWvbmQ5gQA8qz5lCsVIABjsuz8"
open_id_issuer   = "https://dev-lr8vwbeyc7gmi0w2.us.auth0.com/"
keep_warm        = "true"
